version: '3.8'

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    volumes:
      - ./config:/etc/cassandra
      - ../_datastore/cassandra:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=cass_cluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
